site:
  title: Documentation
  url: http:localhost:5000
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://github.com/JakeSCahill/hazelcast-docs-ui/releases/download/v1.1.13/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
    idprefix: ''
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    mc-docs: https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html
    jet-docs: https://docs.hazelcast.org/docs/jet/latest/manual/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
